'use client';

import dynamic from 'next/dynamic';
import { useEffect, useMemo, useRef, useState } from 'react';
import data from '../public/graph.json';

const ForceGraph2D = dynamic(() => import('react-force-graph-2d'), { ssr: false });
type Role='consolidator'|'transit'|'distributor'|'terminal'|'coordinator'|'peripheral';
type Node={id:number;role:Role;role_score:number;cluster_id:number;priority_score:number;evidence:string;is_seed:boolean;depth:number;in_deg:number;out_deg:number;in_kzt:number;out_kzt:number;x?:number;y?:number;fy?:number};
type Link={source:number|Node;target:number|Node;sum_kzt:number;n_tx:number};
const roles:Record<Role,string>={consolidator:'КОНСОЛИДАЦИЯ',transit:'ТРАНЗИТ',distributor:'РАСПРЕДЕЛЕНИЕ',terminal:'ТЕРМИНАЛ',coordinator:'КООРДИНАЦИЯ',peripheral:'ПЕРИФЕРИЯ'};
const roleColor:Record<Role,string>={consolidator:'#A3E635',transit:'#86EFAC',distributor:'#5FC66E',terminal:'#D9FF8C',coordinator:'#C4B5FD',peripheral:'#303833'};
const layerNames=['ПОВЕРХНОСТЬ · ИЗВЕСТНЫЕ КУРЬЕРЫ','КОЛЕНО 1','КОЛЕНО 2','КОЛЕНО 3','КОЛЕНО 4'];
const idOf=(v:number|Node)=>typeof v==='number'?v:v.id;
const money=(v:number)=>v>=1e6?`${(v/1e6).toLocaleString('ru-RU',{maximumFractionDigits:1})} млн ₸`:`${Math.round(v/1000)} тыс. ₸`;
const pct=(v:number)=>`${(v*100).toLocaleString('ru-RU',{minimumFractionDigits:1,maximumFractionDigits:1})}%`;

export default function NetworkAnalysis(){
 const graphRef=useRef<any>(null); const graphBox=useRef<HTMLElement|null>(null); const [size,setSize]=useState({width:900,height:560}); const [tab,setTab]=useState<'graph'|'top'>('graph'); const [filtersOpen,setFiltersOpen]=useState(true);
 const [role,setRole]=useState('all'); const [cluster,setCluster]=useState('all'); const [query,setQuery]=useState(''); const [selected,setSelected]=useState<Node|null>(null);
 const [blocked,setBlocked]=useState<Set<number>>(new Set()); const [withered,setWithered]=useState<Set<number>>(new Set()); const [wave,setWave]=useState<Set<number>>(new Set());
 const nodes=data.nodes as Node[]; const links=data.links as Link[];
 const shown=useMemo(()=>nodes.filter(n=>(role==='all'||n.role===role)&&(cluster==='all'||n.cluster_id===+cluster)).map(n=>({...n,fy:n.depth*105-210,x:n.depth===4?((n.id%3)-1)*185:undefined})),[nodes,role,cluster]);
 const shownIds=useMemo(()=>new Set(shown.map(n=>n.id)),[shown]); const shownLinks=useMemo(()=>links.filter(l=>shownIds.has(idOf(l.source))&&shownIds.has(idOf(l.target))),[links,shownIds]);
 const turnover=shownLinks.reduce((s,l)=>s+l.sum_kzt,0); const totalSeeds=nodes.filter(n=>n.is_seed).length; const deadSeeds=nodes.filter(n=>n.is_seed&&withered.has(n.id)).length;
 const focus=(node?:Node)=>{if(!node)return;setSelected(node);setTab('graph');setTimeout(()=>{graphRef.current?.centerAt(node.x,node.y,500);graphRef.current?.zoom(2.8,500)},80)};
 const search=(e:React.FormEvent)=>{e.preventDefault();focus(nodes.find(n=>String(n.id)===query.trim()))};
 useEffect(()=>{const el=graphBox.current;if(!el)return;const update=()=>setSize({width:el.clientWidth,height:el.clientHeight});update();const observer=new ResizeObserver(update);observer.observe(el);return()=>observer.disconnect()},[tab]);
 useEffect(()=>{if(tab==='graph')setTimeout(()=>{graphRef.current?.d3Force('charge')?.strength((n:Node)=>n.depth===4?-360:-42);graphRef.current?.d3Force('link')?.distance((l:Link)=>(l.target as Node).depth===4?120:42)},80)},[tab,shown]);
 useEffect(()=>{if(tab!=='graph'||!shown.length)return;const timers=[450,1400,2800].map(ms=>setTimeout(()=>graphRef.current?.zoomToFit(650,88),ms));return()=>timers.forEach(clearTimeout)},[tab,shown,shownLinks,filtersOpen,size]);
 useEffect(()=>{if(selected&&!shownIds.has(selected.id))setSelected(null)},[shownIds,selected]);
 const incoming=selected?links.filter(l=>idOf(l.target)===selected.id).map(l=>({node:nodes.find(n=>n.id===idOf(l.source))!,sum:l.sum_kzt})):[];
 const outgoing=selected?links.filter(l=>idOf(l.source)===selected.id).map(l=>({node:nodes.find(n=>n.id===idOf(l.target))!,sum:l.sum_kzt})):[];
 const simulate=()=>{if(!selected||blocked.has(selected.id))return;const ancestors=new Map<number,number>();let frontier=[selected.id],level=0;while(frontier.length){const next:number[]=[];for(const target of frontier)for(const l of links)if(idOf(l.target)===target){const p=idOf(l.source);if(!ancestors.has(p)&&p!==selected.id){ancestors.set(p,level+1);next.push(p)}}frontier=next;level++}setBlocked(p=>new Set(p).add(selected.id));for(let d=0;d<=level;d++){const ids=Array.from(ancestors.entries()).filter(([,x])=>x===d).map(([id])=>id);setTimeout(()=>{setWave(new Set(ids));setWithered(p=>new Set(Array.from(p).concat(ids,[selected.id])))},d*240)}setTimeout(()=>setWave(new Set()),(level+1)*240)};
 const reset=()=>{setBlocked(new Set());setWithered(new Set());setWave(new Set())};
 const paintNode=(raw:any,ctx:CanvasRenderingContext2D,scale:number)=>{const n=raw as Node,x=n.x??0,y=n.y??0,dead=withered.has(n.id)||blocked.has(n.id),core=n.role==='consolidator'||n.role==='terminal',pulse=1+Math.sin(Date.now()/650+n.id)*.07;let r=n.is_seed?2.35:core?(7+n.priority_score*6)*pulse:n.role==='coordinator'?5:n.role==='peripheral'?1.8:2.5;let c=n.is_seed?'#E7ECF7':roleColor[n.role];if(dead)c='#343A3D';if(!dead&&(core||n.role==='coordinator')){ctx.beginPath();ctx.arc(x,y,r+10/scale,0,Math.PI*2);ctx.fillStyle=`${c}18`;ctx.fill();ctx.beginPath();ctx.arc(x,y,r+3/scale,0,Math.PI*2);ctx.strokeStyle=`${c}99`;ctx.lineWidth=1/scale;ctx.stroke()}ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=c;ctx.globalAlpha=n.role==='peripheral'?.58:dead?.26:1;ctx.fill();ctx.globalAlpha=1;if(core){ctx.font=`${9/scale}px var(--font-mono)`;ctx.textAlign='center';ctx.fillStyle=dead?'#596164':'#D9DFEF';ctx.fillText(`GID ${n.id}`,x,y+(r+14/scale))}if(wave.has(n.id)){ctx.beginPath();ctx.arc(x,y,r+13/scale,0,Math.PI*2);ctx.strokeStyle='#E0E5EE';ctx.lineWidth=1/scale;ctx.stroke()}if(selected?.id===n.id){ctx.beginPath();ctx.arc(x,y,r+5/scale,0,Math.PI*2);ctx.strokeStyle='#FFFFFF';ctx.lineWidth=1.2/scale;ctx.stroke()}};
 const paintBack=(ctx:CanvasRenderingContext2D,scale:number)=>{ctx.save();ctx.font=`${8/scale}px var(--font-mono)`;for(let d=0;d<5;d++){const y=d*105-210;ctx.beginPath();ctx.setLineDash([4/scale,8/scale]);ctx.moveTo(-700,y);ctx.lineTo(700,y);ctx.strokeStyle='rgba(124,242,192,.11)';ctx.lineWidth=.7/scale;ctx.stroke();ctx.fillStyle='rgba(174,185,216,.58)';ctx.fillText(layerNames[d],-250,y-8/scale)}ctx.restore()};
 return <main className="screen"><div className="noise"/><Header tab={tab} setTab={setTab}/><Kpis nodes={shown.length} links={shownLinks.length} turnover={turnover} seeds={shown.filter(n=>n.is_seed).length} cores={shown.filter(n=>n.role==='consolidator').length}/><div className="workspace">
  {tab==='graph'?<><aside className={`filters hud ${filtersOpen?'open':'closed'}`}><button className="collapse" onClick={()=>setFiltersOpen(v=>!v)}>{filtersOpen?'‹':'›'}</button>{filtersOpen&&<><Label>ФИЛЬТРЫ СЕТИ</Label><Field label="ПРИЗНАКИ РОЛИ" value={role} set={setRole} options={Object.entries(roles)}/><Field label="КЛАСТЕР" value={cluster} set={setCluster} options={data.clusters.map(c=>[String(c.cluster_id),`КЛАСТЕР ${c.cluster_id}`])}/><div className="rule"/><Label>ЛЕГЕНДА РОЛЕЙ</Label>{Object.entries(roles).map(([r,l])=><div className="legend" key={r}><i style={{background:roleColor[r as Role]}}/>{l}</div>)}</>}</aside><section ref={graphBox} className="graph hud"><div className="toolbar"><form onSubmit={search}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="GID / ПОИСК"/><button>НАЙТИ</button></form><span>ПОТОКИ ПО ГЛУБИНЕ · 5 УРОВНЕЙ</span></div><ForceGraph2D ref={graphRef} width={size.width} height={size.height} graphData={{nodes:shown,links:shownLinks}} backgroundColor="rgba(0,0,0,0)" nodeCanvasObject={paintNode} nodePointerAreaPaint={(n:any,c:string,ctx:CanvasRenderingContext2D)=>{ctx.beginPath();ctx.arc(n.x,n.y,9,0,Math.PI*2);ctx.fillStyle=c;ctx.fill()}} onRenderFramePre={paintBack} cooldownTicks={120} d3AlphaDecay={.035} linkColor={(l:any)=>withered.has(idOf(l.source))||withered.has(idOf(l.target))?'rgba(80,86,88,.08)':(['transit','distributor'].includes((l.source as Node).role)?'rgba(124,242,192,.32)':'rgba(124,242,192,.16)')} linkWidth={(l:any)=>Math.min(2.3,.25+l.sum_kzt/750000)} linkDirectionalArrowLength={4} linkDirectionalArrowRelPos={.97} linkDirectionalParticles={(l:any)=>withered.has(idOf(l.source))||withered.has(idOf(l.target))?0:1} linkDirectionalParticleWidth={1.5} linkDirectionalParticleSpeed={.003} linkDirectionalParticleColor="#7CF2C0" onNodeClick={(n:any)=>focus(n)}/></section>{selected&&<NodeDrawer node={selected} incoming={incoming} outgoing={outgoing} focus={focus} simulate={simulate} reset={reset} isBlocked={blocked.has(selected.id)} deadSeeds={deadSeeds} totalSeeds={totalSeeds} anyBlocked={blocked.size>0} close={()=>setSelected(null)}/>}</>:<TopList nodes={nodes} focus={focus}/>}</div></main>
}
function Header({tab,setTab}:{tab:string;setTab:(v:'graph'|'top')=>void}){return <header className="header hud"><div className="brand"><Logo/><div><b>Грибница</b><small>Курьеров срывают — сеть остаётся</small></div></div><nav><button className={tab==='graph'?'active':''} onClick={()=>setTab('graph')}>Анализ сети</button><button className={tab==='top'?'active':''} onClick={()=>setTab('top')}>Топ-лист</button><button>Лестница денег</button><button>Справка ИИ</button></nav><span className="status">● Анализ активен</span></header>}
function Logo(){return <svg viewBox="0 0 38 32"><path d="M3 6h11l5 7 7-4 9 7M7 27l8-8 7 5 11-4"/><circle cx="3" cy="6" r="2"/><circle cx="19" cy="13" r="2"/><circle cx="35" cy="16" r="2"/><circle cx="7" cy="27" r="2"/><circle cx="22" cy="24" r="2"/></svg>}
function Kpis(p:{nodes:number;links:number;turnover:number;seeds:number;cores:number}){return <div className="kpis"><Kpi n={p.nodes} l="УЗЛОВ В СЕТИ"/><Kpi n={p.links} l="СВЯЗЕЙ"/><Kpi n={money(p.turnover)} l="ОБОРОТ"/><Kpi n={p.seeds} l="ИЗВЕСТНЫХ КУРЬЕРОВ"/><Kpi n={p.cores} l="ТОЧЕК КОНСОЛИДАЦИИ"/></div>}
function Kpi({n,l}:{n:string|number;l:string}){return <div><b>{n}</b><span>{l}</span></div>}
function Label({children}:{children:React.ReactNode}){return <p className="label">{children}</p>}
function Field({label,value,set,options}:{label:string;value:string;set:(v:string)=>void;options:string[][]}){return <label className="field"><span>{label}</span><select value={value} onChange={e=>set(e.target.value)}><option value="all">ВСЕ</option>{options.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label>}
function Badge({role}:{role:Role}){return <span className="badge" style={{color:roleColor[role],borderColor:`${roleColor[role]}55`}}>{roles[role]}</span>}
function NodeDrawer(p:{node:Node;incoming:{node:Node;sum:number}[];outgoing:{node:Node;sum:number}[];focus:(n:Node)=>void;simulate:()=>void;reset:()=>void;isBlocked:boolean;deadSeeds:number;totalSeeds:number;anyBlocked:boolean;close:()=>void}){return <aside className="drawer hud"><button className="x" onClick={p.close}>×</button><Label>NODE INSPECTION</Label><div className="node-title"><b>{p.node.id}</b><Badge role={p.node.role}/></div><p className="muted">ПРИЗНАКИ РОЛИ · {pct(p.node.role_score)}</p><div className="meter"><i style={{width:pct(p.node.role_score)}}/></div><div className="evidence"><Label>ПРИЗНАКИ РОЛИ</Label>{p.node.evidence}</div><Flows title="ПОЛУЧАЛ ОТ" rows={p.incoming} focus={p.focus}/><Flows title="ОТДАВАЛ" rows={p.outgoing} focus={p.focus}/>{p.anyBlocked&&<div className="impact">{p.deadSeeds} ИЗ {p.totalSeeds} ИЗВЕСТНЫХ КУРЬЕРОВ ТЕРЯЮТ СВЯЗЬ С ЗАБЛОКИРОВАННЫМИ УЗЛАМИ</div>}<button className="simulate" disabled={p.isBlocked} onClick={p.simulate}>{p.isBlocked?'УЗЕЛ ОТКЛЮЧЁН':'СМОДЕЛИРОВАТЬ БЛОКИРОВКУ'}</button>{p.anyBlocked&&<button className="reset" onClick={p.reset}>СБРОСИТЬ МОДЕЛИРОВАНИЕ</button>}</aside>}
function Flows({title,rows,focus}:{title:string;rows:{node:Node;sum:number}[];focus:(n:Node)=>void}){return <div className="flows"><Label>{title} · {rows.length}</Label>{rows.slice(0,6).map(r=><button onClick={()=>focus(r.node)} key={r.node.id}><span>{r.node.id}</span><em>{money(r.sum)}</em></button>)}</div>}
function TopList({nodes,focus}:{nodes:Node[];focus:(n:Node)=>void}){return <section className="top hud"><Label>PRIORITY QUEUE / HYPOTHESES</Label><h1>Рекомендуем проверить</h1><table><thead><tr><th>РАНГ</th><th>GID</th><th>ПРИЗНАКИ РОЛИ</th><th>ПРИОРИТЕТ</th><th>ОБОСНОВАНИЕ</th></tr></thead><tbody>{data.top.map(x=><tr key={x.gid} onClick={()=>focus(nodes.find(n=>n.id===x.gid)!)}><td>{x.rank}</td><td>{x.gid}</td><td><Badge role={x.role as Role}/></td><td><div className="bar"><i style={{width:pct(x.priority_score)}}/></div>{pct(x.priority_score)}</td><td>{x.why}</td></tr>)}</tbody></table></section>}
